trigger:
  branches:
    include:
      - main
    exclude:
      - feature/*
pr: none

variables:
- group: Dev-varaible-Group
- name: display my name
  value: $(variables.myname)
steps:
  - script: echo $(myname)

 
